### ISSUE TITLE
Add InlineLink Component to Psammead

### ISSUE THREAD

**Issue by sareh** [BBC-archive/psammead#38]
**Is your feature request related to a problem? Please describe.**
We should add the InlineLink component to this component library.

Corresponding issue in Simorgh: https://github.com/BBC-News/simorgh/issues/1057

Currently it is visible here in the Simorgh repository: https://github.com/BBC-News/simorgh/tree/latest/src/app/components/InlineLink

This work is pending these tickets

- [x]  Reconcile InlineLink (currently have two forked versions): https://github.com/BBC-News/simorgh/issues/887
- [x]  Utilities https://github.com/BBC-News/psammead/issues/32 
- ~Storybook https://github.com/BBC-News/psammead/issues/37~ deprioritised
- [x] Definition of done https://github.com/BBC-News/psammead/issues/36
- [x] Headings #12 (since this component was decided as being the first to be moved over)
- [x] Remove the Headings component from Simorgh & use the one from Psammead https://github.com/BBC-News/simorgh/issues/975

We don't want to start this issue until we have completed the Headings ones. 

**Describe the solution you'd like**
A component for InlineLink. It should meet the definition of done listed in issue #36.

**Describe alternatives you've considered**
N/A

**Testing notes**
There should be unit tests.

**Additional context**
N/A

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/psammead/labels/Refinement%20Needed)

**Comment by ChrisBAshton** [comment]
No longer blocked on reconciliation 🎉
